services:
  dooms-deal-clock:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dooms-deal-clock
    restart: unless-stopped
    
    environment:
      # Telegram API configuration
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_PHONE=${TELEGRAM_PHONE}
      - TELEGRAM_CHANNEL_USERNAME=${TELEGRAM_CHANNEL_USERNAME:-dooms_deal_clock}
      
      # API configuration
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DEBUG=${DEBUG:-false}
      
      # Database configuration
      - DATABASE_URL=sqlite:///./data/clock_data.db
      
      # Update configuration
      - UPDATE_INTERVAL_SECONDS=${UPDATE_INTERVAL_SECONDS:-300}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    
    ports:
      - "8000:8000"
    
    volumes:
      # Persistent data storage
      - app_data:/app/data
      # Optional: Mount logs directory for easier access
      - app_logs:/app/logs
    
    networks:
      - app_network
    
    # Resource limits to prevent resource exhaustion
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "from app.config import config; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:alpine
    container_name: dooms-deal-nginx
    restart: unless-stopped
    
    ports:
      - "80:80"
    
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web:/usr/share/nginx/html:ro
    
    depends_on:
      - dooms-deal-clock
    
    networks:
      - app_network

volumes:
  app_data:
    driver: local
  app_logs:
    driver: local

networks:
  app_network:
    driver: bridge